# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.all.destroy_all()
Monster.all.destroy_all()
Item.all.destroy_all()
User.create(name:"jared", hp:10, att:1)
User.create(name:"stan",hp:99, att: 99)

Monster.create(name:"bleh", hp:5, att:1, img:"")
Monster.create(name:"Jack o Lantern", hp: 10, att:5, img:"https://images-na.ssl-images-amazon.com/images/I/71VUHEvpjFL._SY679_.jpg")
Monster.create(name:"Zombie", hp: 10, att:5, img:"https://d3n8a8pro7vhmx.cloudfront.net/miclimateaction/pages/44/attachments/original/1476899423/shutterstock_zombie.jpg.CROP.original-original.jpg?1476899423")
Monster.create(name:"Mummy", hp: 10, att:5, img:"https://img.pixers.pics/pho_wat(s3:700/FO/56/19/16/00/700_FO56191600_59b1c0a76efb6eabad0a5a2a466e7121.jpg,449,700,cms:2018/10/5bd1b6b8d04b8_220x50-watermark.png,over,229,650,jpg)/wall-murals-cartoon-illustration-of-scary-halloween-mummy.jpg.jpg")
Monster.create(name:"Mike Tyson", hp: 10, att:5, img:"https://cdn.wikimg.net/en/strategywiki/images/a/a2/SSF2T_Balrog.gif")
Monster.create(name:"Werewolf", hp: 10, att:5, img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRZk0F3E7B8A5DFedEHAbdligS9FbZj8vVhrrBCGQztq2DL7r7-Q&s")
Monster.create(name:"Frankenstein", hp: 10, att:5, img:"https://miro.medium.com/max/600/0*J9UxKvD0Mngh3QWC.jpg")
Monster.create(name:"Headless", hp: 10, att:5, img:"https://sc-events.s3.amazonaws.com/8596/5535692/1be3466fa3388b950a8f0dff8273ee2e964d7204328558994b6128de42ffc975/0d00e1f9-7adf-4560-955e-82a570f870bc.jpg")
Monster.create(name:"Dracula", hp: 10, att:5, img:"https://static.tvtropes.org/pmwiki/pub/images/bela_lugosi_as_dracula.jpeg")
Monster.create(name:"Nosferatu", hp: 10, att:5, img:"https://i.redd.it/6104c86np1t21.jpg")
Monster.create(name:"The Creature", hp: 10, att:5, img:"https://images-na.ssl-images-amazon.com/images/I/91795J0d2XL._SX342_.jpg")
Monster.create(name:"Devil", hp: 10, att:5, img:"https://vignette.wikia.nocookie.net/simpsons/images/7/7c/Devil_Flanders.png/revision/latest?cb=20141121004306")
Monster.create(name:"Jeff Bezos", hp: 10, att:5, img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA7zcEva1qUmuAMss1t2Qrl-NCn9uloRdZr6z8p4SDn8Fx9Urq&s")

Item.create(name:"Wood Sword", hp:0, att:2, description:"Maybe it'll cut them, maybe it'll give them some bruises. Who knows?", buyprice:2, sellprice:1 )
Item.create(name:"Iron Sword", hp:0, att:4, description:"A squire's first real weapon.", buyprice: 4, sellprice:2 )
Item.create(name:"Silver Sword", hp:0, att:5, description:"Better than iron.", buyprice: 6, sellprice:3 )
Item.create(name:"Gold Sword", hp:0, att:8, description:"Oooo Shiny!", buyprice: 8, sellprice: 4)
Item.create(name:"Platinum Sword", hp:0, att:10, description:"Better than gold.", buyprice:10 , sellprice: 5)
Item.create(name:"Diamond Sword", hp:0, att:12, description:"Oooo Shinier!", buyprice: 12, sellprice: 6)
Item.create(name:"Master Sword", hp:0, att:14, description:"Better than diamond.", buyprice: 14, sellprice: 7)
Item.create(name:"Challenger Sword", hp:0, att:16, description:"Shiniest... or is it?", buyprice: 16, sellprice: 8)
Item.create(name:"Infinity Edge", hp:0, att:20, description:"Forged by the Gods!", buyprice: 18, sellprice: 9)

Item.create(name:"Wood Armor", hp:2, att:0, description:"Will stop a sword if the sword is wooden.", buyprice:2, sellprice:1)
Item.create(name:"Iron Armor", hp:4, att:0, description:"A squire's first real armor", buyprice:4, sellprice:2)
Item.create(name:"Silver Armor", hp:6, att:0, description:"Better than iron.", buyprice:6, sellprice:3)
Item.create(name:"Gold Armor", hp:8, att:0, description:"Will attract the fairest damsels in the land.", buyprice:8, sellprice:4)
Item.create(name:"Platinum Armor", hp:10, att:0, description:"A rapper's most wanted item.", buyprice:10, sellprice:5)
Item.create(name:"Diamond Armor", hp:12, att:0, description:"Diamonds are forever.", buyprice:12, sellprice:6)
Item.create(name:"Master Armor", hp:14, att:0, description:"Master Chief would be proud.", buyprice:14, sellprice:7)
Item.create(name:"Challenger Armor", hp:16, att:0, description:"You'll be ready to take on the world.", buyprice:16, sellprice:8)
Item.create(name:"Warmog's Armor", hp:20, att:0, description:"You are a warmonger.", buyprice:18, sellprice:9)

Item.create(name:"Wood Shield", hp:1, att:1, description:"Link's first shield.", buyprice: 2, sellprice: 1)
Item.create(name:"Iron Shield", hp:2, att:2, description:"Pantheon's shield.", buyprice: 4, sellprice:2 )
Item.create(name:"Silver Shield", hp:3, att:3, description:"Standard shield of The Army of Doom.", buyprice: 6, sellprice:3 )
Item.create(name:"Gold Shield", hp:4, att:4, description:"Heavy but valueable", buyprice: 8, sellprice: 4)
Item.create(name:"Platinum Shield", hp:5, att:5, description:"Even more valueable than a gold shield", buyprice: 10, sellprice: 5)
Item.create(name:"Diamond Shield", hp:6, att:6, description:"Damn this thing is cool", buyprice: 12, sellprice: 6)
Item.create(name:"Master Shield", hp:7, att:7, description:"Obey your master", buyprice: 14, sellprice: 7)
Item.create(name:"Challenger Shield", hp:8, att:8, description:"You are the best", buyprice: 16, sellprice: 8)
Item.create(name:"Stan's Shield of Stunning Standing Starry Stupid Stuff", hp:10, att:10, description:"You are the best", buyprice: 18, sellprice: 9)

Item.create(name:"Wood Boots", hp:1, att:1, description:"Not very comfortable", buyprice:2, sellprice:1)
Item.create(name:"Iron Boots", hp:2, att:2, description:"Still uncomfortable but a lot healthier", buyprice:4, sellprice:2)
Item.create(name:"Silver Boots", hp:3, att:3, description:"Can kill a vampire by kicking him", buyprice:6, sellprice:3)
Item.create(name:"Gold Boots", hp:4, att:4, description:"Michael Jordan would be jealous", buyprice:8, sellprice:4)
Item.create(name:"Platinum Boots", hp:5, att:5, description:"Migos would be jealous", buyprice:10, sellprice:5)
Item.create(name:"Diamond Boots", hp:6, att:6, description:"Will cut your toes up", buyprice:12, sellprice:6)
Item.create(name:"Master Boots", hp:7, att:7, description:"Makes you jump high", buyprice:14, sellprice:7)
Item.create(name:"Challenger Boots", hp:8, att:8, description:"Usain Bolt made these with his bare hands", buyprice:16, sellprice:8)
Item.create(name:"Booties of Thy Jared", hp:10, att:10, description:"Made by Jared's mum Debbie", buyprice:18, sellprice:9)


